# Shell variables
# Generated by 'wal'
wallpaper='/home/uzuto/Pictures/wallpapers/RadioactiveSunrise.jpg'

# Special
background='#090506'
foreground='#f5c69a'
cursor='#f5c69a'

# Colors
color0='#090506'
color1='#CC3526'
color2='#F15A35'
color3='#9E3850'
color4='#C83D48'
color5='#9B476B'
color6='#D94749'
color7='#f5c69a'
color8='#ab8a6b'
color9='#CC3526'
color10='#F15A35'
color11='#9E3850'
color12='#C83D48'
color13='#9B476B'
color14='#D94749'
color15='#f5c69a'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"

# Don't Delete This File
