# Shell variables
# Generated by 'wal'
wallpaper='/home/uzuto/Pictures/wallpapers/odin-dark.jpg'

# Special
background='#030C0E'
foreground='#bfd6d1'
cursor='#bfd6d1'

# Colors
color0='#030C0E'
color1='#28504C'
color2='#1E6B61'
color3='#496F6F'
color4='#278E72'
color5='#427788'
color6='#4CBFA4'
color7='#bfd6d1'
color8='#859592'
color9='#28504C'
color10='#1E6B61'
color11='#496F6F'
color12='#278E72'
color13='#427788'
color14='#4CBFA4'
color15='#bfd6d1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"

# Don't Delete This File
